
export const GET_LIKES_SUCCESS = "GET_LIKES_SUCCESS"
export const GET_LIKES_ERROR = "GET_LIKES_ERROR"
export const LIKE_CREATE_SUCCESS = "LIKE_CREATE_SUCCESS"
export const LIKE_CREATE_ERROR = "LIKE_CREATE_ERROR"
export const LIKE_DELETE_SUCCESS = "LIKE_DELETE_SUCCESS"
export const LIKE_DELETE_ERROR = "LIKE_DELETE_ERROR"

