export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_ERROR = "CREATE_POST_ERROR"
export const CREATE_POST = "CREATE_POST"
export const FETCH_POSTS = "FETCH_POSTS"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"




